### ISSUE TITLE
Special character handling

### ISSUE THREAD

**Issue by CovatiGW** [Laharah/deluge-FileBotTool#2] opened 2016-03-03 23:15 UTC
`FilebotRuntimeError error on torrent ----:
    FILEBOT OUTPUT DUMP:
    Rename music using [ID3 Tags]
    IOException: MediaInfo failed to open file: D:\Raw_download\SKR_WBERRiES.FUNR_iSRS VOL.3\05 KÂºultrâˆ†ynin.mp3
    java.io.IOException: MediaInfo failed to open file: D:\Raw_download\SKR_WBERRiES.FUNR_iSRS VOL.3\05 KÂºultrâˆ†ynin.mp3
    	at net.filebot.web.ID3Lookup.lookup(ID3Lookup.java:36)
    	at net.filebot.cli.CmdlineOperations.renameMusic(CmdlineOperations.java:521)
    	at net.filebot.cli.CmdlineOperations.rename(CmdlineOperations.java:108)
    	at net.filebot.cli.ArgumentProcessor.process(ArgumentProcessor.java:79)
    	at net.filebot.Main.main(Main.java:169)
    Failure (°_°)
    `
Deluge screwed up the special chars first and it gave the same error, filebot is able to process the files when manually sorted.

**Comment by Laharah** [comment] 2016-03-04 00:38
Yeah, that's a known issue. Unfortunately, I couldn't find much that I could do about it. Python 2 has trouble calling executable arguments with certain character encodings. The issue is fixed in python 3, but it's not going to be fixed for python2. 

I'm keeping an eye out for a good workaround, because everything I've come up with is pretty hacky. Right now if you've only got one or two files that are causing problems, you can manually rename them in deluge (in the files tab in the torrent view) to something that uses only ASCII characters, then run filebottool, and the names should be returned to deluge with everything correct.

**Comment by Laharah** [comment] 2016-08-07 23:27
This problem should now be fixed in the initial 1.0 release.

**Closed by Laharah** 2016-08-07 23:27 UTC
